export const serverAddress = 'http://localhost:5000';

export const GET_USERS = "GET_USERS";
export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS_FULFILLED = "GET_USERS_FULFILLED";
export const GET_USERS_REJECTED = "GET_USERS_REJECTED";

export const GET_USER = "GET_USER";
export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";

export const ADD_USER = "ADD_USER";
export const ADD_USER_PENDING = "ADD_USER_PENDING";
export const ADD_USER_FULFILLED = "ADD_USER_FULFILLED";
export const ADD_USER_REJECTED = "ADD_USER_REJECTED";

export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_PENDING = "REMOVE_USER_PENDING";
export const REMOVE_USER_FULFILLED = "REMOVE_USER_FULFILLED";
export const REMOVE_USER_REJECTED = "REMOVE_USER_REJECTED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";

export const SET_ID = "SET_ID"
export const SET_ID_PENDING = "SET_ID_PENDING";
export const SET_ID_FULFILLED = "SET_ID_FULFILLED";
export const SET_ID_REJECTED = "SET_ID_REJECTED";
